//! dupfinder — duplication detection + reuse discovery for Rust, TypeScript,
//! and Functor Lang. Three engines: an API index (prevention), local code
//! embeddings (semantic similarity), and jscpd (token clones).

use anyhow::Result;
use clap::{Parser, Subcommand};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

mod clones;
mod embedder;
mod extract;
mod gitdiff;
mod store;

#[derive(Parser)]
#[command(name = "dupfinder", version, about)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Emit a consolidated API index (functions + types) as markdown
    Index {
        #[arg(default_value = ".")]
        path: PathBuf,
        /// Include non-public/non-exported items
        #[arg(long)]
        private: bool,
        /// Write to a file instead of stdout
        #[arg(long)]
        out: Option<PathBuf>,
    },
    /// Build or incrementally update the embedding index (.dupfinder/)
    Embed {
        #[arg(default_value = ".")]
        path: PathBuf,
    },
    /// Most similar function pairs across the whole index
    Similar {
        #[arg(default_value = ".")]
        path: PathBuf,
        #[arg(long, default_value_t = 0.9)]
        threshold: f32,
        #[arg(long, default_value_t = 40)]
        top: usize,
        #[arg(long, default_value_t = 6)]
        min_lines: u32,
        /// Include test functions
        #[arg(long)]
        include_tests: bool,
    },
    /// Token-level copy-paste clones via jscpd (needs npx)
    Clones {
        #[arg(default_value = ".")]
        path: PathBuf,
    },
    /// Duplication review of the current change vs a base ref:
    /// token clones touching the diff + similar existing code per changed function
    Review {
        #[arg(default_value = ".")]
        path: PathBuf,
        /// Base ref (default: origin/main, origin/master, main, or master)
        #[arg(long)]
        base: Option<String>,
        /// Similar existing functions to list per changed function
        #[arg(long, default_value_t = 3)]
        top: usize,
        /// Ignore changed functions smaller than this
        #[arg(long, default_value_t = 5)]
        min_lines: u32,
    },
}

fn main() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::Index { path, private, out } => cmd_index(&path, private, out),
        Cmd::Embed { path } => {
            store::build_or_update(&path)?;
            eprintln!("[dupfinder] index up to date in {}/{}", path.display(), store::DIR);
            Ok(())
        }
        Cmd::Similar { path, threshold, top, min_lines, include_tests } => {
            cmd_similar(&path, threshold, top, min_lines, include_tests)
        }
        Cmd::Clones { path } => cmd_clones(&path),
        Cmd::Review { path, base, top, min_lines } => cmd_review(&path, base, top, min_lines),
    }
}

// ---------------------------------------------------------------- index

fn cmd_index(root: &Path, include_private: bool, out: Option<PathBuf>) -> Result<()> {
    let ex = extract::extract_dir(root)?;
    let mut md = String::from("# API index\n\nGenerated by dupfinder. Grep here for an existing helper before writing a new one.\n");
    let mut files: BTreeSet<&str> = BTreeSet::new();
    for r in &ex.fns {
        files.insert(&r.file);
    }
    for t in &ex.types {
        files.insert(&t.file);
    }
    let mut n = 0usize;
    for file in files {
        let mut section = String::new();
        for t in ex.types.iter().filter(|t| t.file == file) {
            if !(t.public || include_private) {
                continue;
            }
            section.push_str(&format!("- {} `{}`", t.kind, t.name));
            if !t.doc.is_empty() {
                section.push_str(&format!(" — {}", first_sentence(&t.doc)));
            }
            section.push_str(&format!("  ({}:{})\n", t.file, t.start));
            n += 1;
        }
        for r in ex.fns.iter().filter(|r| r.file == file) {
            if !(r.public || include_private) || r.is_testish() {
                continue;
            }
            let sig = r.sig.replace("pub fn ", "fn ").replace("pub(crate) fn ", "fn ");
            section.push_str(&format!("- `{}`", clip(&sig, 150)));
            if !r.doc.is_empty() {
                section.push_str(&format!(" — {}", first_sentence(&r.doc)));
            }
            section.push_str(&format!("  ({}:{})\n", r.file, r.start));
            n += 1;
        }
        if !section.is_empty() {
            md.push_str(&format!("\n## {file}\n{section}"));
        }
    }
    eprintln!("[dupfinder] indexed {n} items");
    match out {
        Some(p) => std::fs::write(p, md)?,
        None => print!("{md}"),
    }
    Ok(())
}

fn first_sentence(doc: &str) -> String {
    let s = doc.split(". ").next().unwrap_or(doc);
    clip(s, 110)
}

fn clip(s: &str, max: usize) -> String {
    match s.char_indices().nth(max) {
        Some((i, _)) => format!("{}…", &s[..i]),
        None => s.to_string(),
    }
}

// -------------------------------------------------------------- similar

fn cmd_similar(root: &Path, threshold: f32, top: usize, min_lines: u32, include_tests: bool) -> Result<()> {
    let st = store::build_or_update(root)?;
    let keep: Vec<usize> = st
        .records
        .iter()
        .enumerate()
        .filter(|(_, r)| r.lines >= min_lines && (include_tests || !r.is_testish()))
        .map(|(i, _)| i)
        .collect();
    let mut pairs: Vec<(f32, usize, usize)> = Vec::new();
    for (a, &i) in keep.iter().enumerate() {
        for &j in &keep[a + 1..] {
            let (ri, rj) = (&st.records[i], &st.records[j]);
            // Skip a function overlapping itself across near-identical ranges.
            if ri.file == rj.file && ri.start.abs_diff(rj.start) < 5 {
                continue;
            }
            let s = embedder::dot(&st.vectors[i], &st.vectors[j]);
            if s >= threshold {
                pairs.push((s, i, j));
            }
        }
    }
    pairs.sort_by(|x, y| y.0.total_cmp(&x.0));
    println!("# similar pairs (threshold {threshold}, {} candidates)\n", pairs.len());
    for (s, i, j) in pairs.into_iter().take(top) {
        let (a, b) = (&st.records[i], &st.records[j]);
        let tag = if a.name == b.name { "  [same-name]" } else { "" };
        println!("{s:.3}  {}  {} ({}L){tag}", a.name, a.location(), a.lines);
        println!("       {}  {} ({}L)\n", b.name, b.location(), b.lines);
    }
    Ok(())
}

// --------------------------------------------------------------- clones

fn cmd_clones(root: &Path) -> Result<()> {
    match clones::run_jscpd(root)? {
        None => {}
        Some(list) => {
            println!("# token clones (jscpd): {}\n", list.len());
            for c in list {
                println!(
                    "{}:{}-{} <-> {}:{}-{}  ({} lines)",
                    c.file_a, c.a.0, c.a.1, c.file_b, c.b.0, c.b.1, c.lines
                );
            }
        }
    }
    Ok(())
}

// --------------------------------------------------------------- review

fn cmd_review(root: &Path, base: Option<String>, top: usize, min_lines: u32) -> Result<()> {
    let base = gitdiff::resolve_base(root, base)?;
    let changed = gitdiff::changed_ranges(root, &base)?;
    println!("# dupfinder review\n\nBase: `{base}` — {} changed file(s)\n", changed.len());
    if changed.is_empty() {
        println!("No changes to review.");
        return Ok(());
    }

    let st = store::build_or_update(root)?;
    let changed_idx: Vec<usize> = st
        .records
        .iter()
        .enumerate()
        .filter(|(_, r)| {
            changed
                .get(&r.file)
                .is_some_and(|ranges| gitdiff::overlaps(ranges, r.start, r.end))
        })
        .map(|(i, _)| i)
        .collect();
    let changed_set: BTreeSet<usize> = changed_idx.iter().copied().collect();

    // --- token clones touching changed files
    println!("## Token clones touching this change (jscpd)\n");
    match clones::run_jscpd(root)? {
        None => println!("(jscpd unavailable — skipped)\n"),
        Some(list) => {
            let hits: Vec<_> = list
                .iter()
                .filter(|c| changed.keys().any(|f| c.touches(f)))
                .collect();
            if hits.is_empty() {
                println!("None.\n");
            } else {
                for c in hits {
                    println!(
                        "- `{}:{}-{}` <-> `{}:{}-{}` ({} lines)",
                        c.file_a, c.a.0, c.a.1, c.file_b, c.b.0, c.b.1, c.lines
                    );
                }
                println!();
            }
        }
    }

    // --- semantic neighbors per changed function
    println!("## Similar existing code per changed function (embeddings)\n");
    println!("Similarity is rank-meaningful, not absolute — the top neighbor of a genuine re-implementation often scores ~0.5-0.7. Judge by reading the neighbor, not by the number.\n");
    let mut reported = 0usize;
    for &i in &changed_idx {
        let r = &st.records[i];
        if r.lines < min_lines || r.is_testish() {
            continue;
        }
        let mut sims: Vec<(f32, usize)> = st
            .vectors
            .iter()
            .enumerate()
            .filter(|(j, _)| {
                let o = &st.records[*j];
                !(o.file == r.file && o.start.abs_diff(r.start) < 5)
            })
            .map(|(j, v)| (embedder::dot(&st.vectors[i], v), j))
            .collect();
        sims.sort_by(|x, y| y.0.total_cmp(&x.0));
        let neighbors: Vec<_> = sims
            .into_iter()
            .take(top)
            .filter(|(s, _)| *s >= 0.45)
            .collect();
        if neighbors.is_empty() {
            continue;
        }
        reported += 1;
        println!("### `{}`  ({}, {}L, {})", r.name, r.location(), r.lines, r.lang);
        for (s, j) in neighbors {
            let o = &st.records[j];
            let mut tags = Vec::new();
            if changed_set.contains(&j) {
                tags.push("also changed in this diff");
            }
            if o.is_testish() {
                tags.push("test code");
            }
            let tag = if tags.is_empty() {
                String::new()
            } else {
                format!("  [{}]", tags.join(", "))
            };
            let doc = if o.doc.is_empty() {
                String::new()
            } else {
                format!(" — {}", first_sentence(&o.doc))
            };
            println!("- {s:.2}  `{}`  {}{}{}", o.name, o.location(), doc, tag);
        }
        println!();
    }
    if reported == 0 {
        println!("No changed functions with notable neighbors.\n");
    }
    Ok(())
}
