//! dupfinder — duplication detection + reuse discovery for Rust, TypeScript,
//! and Functor Lang. Three engines: an API index (prevention), local code
//! embeddings (semantic similarity), and jscpd (token clones).

use anyhow::Result;
use clap::{Parser, Subcommand};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

mod clones;
mod embedder;
mod extract;
mod gitdiff;
mod names;
mod skill;
mod store;

#[derive(Parser)]
#[command(name = "dupfinder", version, about)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Emit a consolidated API index (functions + types) as markdown
    Index {
        #[arg(default_value = ".")]
        path: PathBuf,
        /// Include non-public/non-exported items
        #[arg(long)]
        private: bool,
        /// Write to a file instead of stdout
        #[arg(long)]
        out: Option<PathBuf>,
    },
    /// Build or incrementally update the embedding index (.dupfinder/)
    Embed {
        #[arg(default_value = ".")]
        path: PathBuf,
    },
    /// Most similar function pairs across the whole index
    Similar {
        #[arg(default_value = ".")]
        path: PathBuf,
        #[arg(long, default_value_t = 0.9)]
        threshold: f32,
        #[arg(long, default_value_t = 40)]
        top: usize,
        #[arg(long, default_value_t = 6)]
        min_lines: u32,
        /// Include test functions
        #[arg(long)]
        include_tests: bool,
    },
    /// Token-level copy-paste clones via jscpd (needs npx)
    Clones {
        #[arg(default_value = ".")]
        path: PathBuf,
    },
    /// Lexical prior-art search: rank existing fns/types by identifier-token
    /// (Jaccard) similarity to what a change adds. No embeddings — milliseconds.
    Names {
        #[arg(default_value = ".")]
        path: PathBuf,
        /// Base ref (default: origin/main, origin/master, main, or master)
        #[arg(long)]
        base: Option<String>,
        /// Score a bare identifier instead of the git diff (repeatable).
        /// Use before writing the function, when there is nothing to diff yet.
        #[arg(long = "name")]
        names: Vec<String>,
        /// Candidates to list per query
        #[arg(long, default_value_t = 5)]
        top: usize,
        /// Hide candidates scoring below this (0.0-1.0)
        #[arg(long, default_value_t = 0.3)]
        min_score: f32,
        /// Include test functions as candidates
        #[arg(long)]
        include_tests: bool,
        /// Audit the WHOLE repo instead of a diff: rank every pair of existing
        /// fns/types, once each, damped by how distinctive their shared words are
        #[arg(long)]
        all: bool,
    },
    /// Duplication review of the current change vs a base ref:
    /// token clones touching the diff + similar existing code per changed function
    Review {
        #[arg(default_value = ".")]
        path: PathBuf,
        /// Base ref (default: origin/main, origin/master, main, or master)
        #[arg(long)]
        base: Option<String>,
        /// Similar existing functions to list per changed function
        #[arg(long, default_value_t = 3)]
        top: usize,
        /// Ignore changed functions smaller than this
        #[arg(long, default_value_t = 5)]
        min_lines: u32,
    },
    /// Install the bundled `review-for-duplicates` Claude Code skill
    InstallSkill {
        /// Install into ./.claude/skills instead of ~/.claude/skills
        #[arg(long)]
        project: bool,
        /// Explicit skills directory (overrides the default location)
        #[arg(long)]
        dir: Option<PathBuf>,
    },
}

fn main() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::Index { path, private, out } => cmd_index(&path, private, out),
        Cmd::Embed { path } => {
            store::build_or_update(&path)?;
            eprintln!("[dupfinder] index up to date in {}/{}", path.display(), store::DIR);
            Ok(())
        }
        Cmd::Similar { path, threshold, top, min_lines, include_tests } => {
            cmd_similar(&path, threshold, top, min_lines, include_tests)
        }
        Cmd::Clones { path } => cmd_clones(&path),
        Cmd::Names { path, base, names, top, min_score, include_tests, all } => {
            cmd_names(&path, base, &names, top, min_score, include_tests, all)
        }
        Cmd::Review { path, base, top, min_lines } => cmd_review(&path, base, top, min_lines),
        Cmd::InstallSkill { project, dir } => skill::install(project, dir),
    }
}

// ---------------------------------------------------------------- index

fn cmd_index(root: &Path, include_private: bool, out: Option<PathBuf>) -> Result<()> {
    let ex = extract::extract_dir(root)?;
    let mut md = String::from("# API index\n\nGenerated by dupfinder. Grep here for an existing helper before writing a new one.\n");
    let mut files: BTreeSet<&str> = BTreeSet::new();
    for r in &ex.fns {
        files.insert(&r.file);
    }
    for t in &ex.types {
        files.insert(&t.file);
    }
    let mut n = 0usize;
    for file in files {
        let mut section = String::new();
        for t in ex.types.iter().filter(|t| t.file == file) {
            if !(t.public || include_private) {
                continue;
            }
            section.push_str(&format!("- {} `{}`", t.kind, t.name));
            if !t.doc.is_empty() {
                section.push_str(&format!(" — {}", first_sentence(&t.doc)));
            }
            section.push_str(&format!("  ({}:{})\n", t.file, t.start));
            n += 1;
        }
        for r in ex.fns.iter().filter(|r| r.file == file) {
            if !(r.public || include_private) || r.is_testish() {
                continue;
            }
            let sig = r.sig.replace("pub fn ", "fn ").replace("pub(crate) fn ", "fn ");
            section.push_str(&format!("- `{}`", clip(&sig, 150)));
            if !r.doc.is_empty() {
                section.push_str(&format!(" — {}", first_sentence(&r.doc)));
            }
            section.push_str(&format!("  ({}:{})\n", r.file, r.start));
            n += 1;
        }
        if !section.is_empty() {
            md.push_str(&format!("\n## {file}\n{section}"));
        }
    }
    eprintln!("[dupfinder] indexed {n} items");
    match out {
        Some(p) => std::fs::write(p, md)?,
        None => print!("{md}"),
    }
    Ok(())
}

fn first_sentence(doc: &str) -> String {
    let s = doc.split(". ").next().unwrap_or(doc);
    clip(s, 110)
}

fn clip(s: &str, max: usize) -> String {
    match s.char_indices().nth(max) {
        Some((i, _)) => format!("{}…", &s[..i]),
        None => s.to_string(),
    }
}

// -------------------------------------------------------------- similar

fn cmd_similar(root: &Path, threshold: f32, top: usize, min_lines: u32, include_tests: bool) -> Result<()> {
    let st = store::build_or_update(root)?;
    let keep: Vec<usize> = st
        .records
        .iter()
        .enumerate()
        .filter(|(_, r)| r.lines >= min_lines && (include_tests || !r.is_testish()))
        .map(|(i, _)| i)
        .collect();
    let mut pairs: Vec<(f32, usize, usize)> = Vec::new();
    for (a, &i) in keep.iter().enumerate() {
        for &j in &keep[a + 1..] {
            let (ri, rj) = (&st.records[i], &st.records[j]);
            // Overlapping ranges in one file = nested/self extraction, not a pair.
            if ri.file == rj.file && ri.start <= rj.end && rj.start <= ri.end {
                continue;
            }
            let s = embedder::dot(&st.vectors[i], &st.vectors[j]);
            if s >= threshold {
                pairs.push((s, i, j));
            }
        }
    }
    pairs.sort_by(|x, y| y.0.total_cmp(&x.0));
    println!("# similar pairs (threshold {threshold}, {} candidates)\n", pairs.len());
    for (s, i, j) in pairs.into_iter().take(top) {
        let (a, b) = (&st.records[i], &st.records[j]);
        let tag = if a.name == b.name { "  [same-name]" } else { "" };
        println!("{s:.3}  {}  {} ({}L){tag}", a.name, a.location(), a.lines);
        println!("       {}  {} ({}L)\n", b.name, b.location(), b.lines);
    }
    Ok(())
}

// --------------------------------------------------------------- clones

fn cmd_clones(root: &Path) -> Result<()> {
    match clones::run_jscpd(root)? {
        None => {}
        Some(list) => {
            println!("# token clones (jscpd): {}\n", list.len());
            for c in list {
                println!(
                    "{}:{}-{} <-> {}:{}-{}  ({} lines)",
                    c.file_a, c.a.0, c.a.1, c.file_b, c.b.0, c.b.1, c.lines
                );
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------- names

#[allow(clippy::too_many_arguments)]
fn cmd_names(
    root: &Path,
    base: Option<String>,
    query_names: &[String],
    top: usize,
    min_score: f32,
    include_tests: bool,
    audit: bool,
) -> Result<()> {
    let ex = extract::extract_dir(root)?;
    let all = names::candidates(&ex);
    if audit {
        return audit_repo(&all, top, min_score, include_tests);
    }

    // Query set: explicit --name identifiers, else whatever the diff touches.
    let queries: Vec<names::Candidate> = if !query_names.is_empty() {
        query_names.iter().map(|n| names::query_from_name(n)).collect()
    } else {
        let base = gitdiff::resolve_base(root, base)?;
        let changed = gitdiff::changed_ranges(root, &base)?;
        println!("Base: `{base}` — {} changed file(s)\n", changed.len());
        all.iter()
            .filter(|c| {
                // Test code is not prior art worth deduping against, and a test
                // is not worth asking about either.
                (include_tests || !c.testish)
                    && changed.get(&c.file).is_some_and(|r| gitdiff::overlaps(r, c.start, c.end))
            })
            .cloned()
            .collect()
    };

    if queries.is_empty() {
        println!("Nothing to check (no changed fns/types, and no --name given).");
        return Ok(());
    }

    println!(
        "# lexical prior art ({} quer{}, {} candidates, min-score {min_score})\n",
        queries.len(),
        if queries.len() == 1 { "y" } else { "ies" },
        all.len()
    );
    println!("Token-overlap only — a rewrite sharing no words scores 0 here. Read the candidate before calling it a duplicate.\n");

    let mut any = false;
    for q in &queries {
        let mut hits: Vec<(f32, f32, f32, &names::Candidate)> = all
            .iter()
            .filter(|c| {
                // Skip the query itself and anything overlapping it.
                (include_tests || !c.testish)
                    && !(c.file == q.file && c.start <= q.end && q.start <= c.end)
            })
            .map(|c| {
                let (s, n, t) = names::score(q, c);
                (s, n, t, c)
            })
            .filter(|(s, ..)| *s >= min_score)
            .collect();
        hits.sort_by(|a, b| b.0.total_cmp(&a.0));
        hits.truncate(top);
        if hits.is_empty() {
            continue;
        }
        any = true;
        if q.kind == "query" {
            println!("### `{}`", q.name);
        } else {
            println!("### `{}`  ({} {})", q.name, q.kind, q.location());
        }
        for (s, n, t, c) in hits {
            let doc = if c.doc.is_empty() {
                String::new()
            } else {
                format!(" — {}", first_sentence(&c.doc))
            };
            println!("- {s:.2}  [name {n:.2} / types {t:.2}]  {} `{}`  {}{}", c.kind, c.name, c.location(), doc);
        }
        println!();
    }
    if !any {
        println!("No lexically similar prior art above {min_score}.");
    }
    Ok(())
}


/// Whole-repo audit: every unordered pair once, ranked by IDF-damped score.
fn audit_repo(all: &[names::Candidate], top: usize, min_score: f32, include_tests: bool) -> Result<()> {
    let idf = names::Idf::build(all);
    let pool: Vec<&names::Candidate> = all
        .iter()
        .filter(|c| (include_tests || !c.testish) && !c.delegating)
        .collect();

    let mut pairs: Vec<(f32, f32, f32, &names::Candidate, &names::Candidate)> = Vec::new();
    for (i, a) in pool.iter().enumerate() {
        for b in &pool[i + 1..] {
            // Overlapping ranges in one file = nested item, not a pair.
            if a.file == b.file && a.start <= b.end && b.start <= a.end {
                continue;
            }
            if names::structurally_forced(a, b) {
                continue;
            }
            let (s, n, t) = names::audit_score(a, b, &idf);
            if s >= min_score {
                pairs.push((s, n, t, a, b));
            }
        }
    }
    pairs.sort_by(|x, y| y.0.total_cmp(&x.0));

    println!("# lexical duplication audit ({} candidates, {} pair(s) over {min_score})\n", pool.len(), pairs.len());
    println!("Score = name/type Jaccard damped by how distinctive the shared words are, so `new` vs `new` sinks and `get_half_pixel` vs `get_half_pixel` floats. Trait impls that share a method name, or just forward to another method, are excluded. Read both sides before calling anything a duplicate.\n");
    for (s, n, t, a, b) in pairs.into_iter().take(top) {
        println!("{s:.2}  [name {n:.2} / types {t:.2}]");
        println!("      {} `{}`  {}", a.kind, a.name, a.location());
        println!("      {} `{}`  {}\n", b.kind, b.name, b.location());
    }
    Ok(())
}

// --------------------------------------------------------------- review

fn cmd_review(root: &Path, base: Option<String>, top: usize, min_lines: u32) -> Result<()> {
    let base = gitdiff::resolve_base(root, base)?;
    let changed = gitdiff::changed_ranges(root, &base)?;
    println!("# dupfinder review\n\nBase: `{base}` — {} changed file(s)\n", changed.len());
    if changed.is_empty() {
        println!("No changes to review.");
        return Ok(());
    }

    let st = store::build_or_update(root)?;
    let changed_idx: Vec<usize> = st
        .records
        .iter()
        .enumerate()
        .filter(|(_, r)| {
            changed
                .get(&r.file)
                .is_some_and(|ranges| gitdiff::overlaps(ranges, r.start, r.end))
        })
        .map(|(i, _)| i)
        .collect();
    let changed_set: BTreeSet<usize> = changed_idx.iter().copied().collect();

    // --- token clones touching changed files
    println!("## Token clones touching this change (jscpd)\n");
    match clones::run_jscpd(root)? {
        None => println!("(jscpd unavailable — skipped)\n"),
        Some(list) => {
            let hits: Vec<_> = list
                .iter()
                .filter(|c| changed.keys().any(|f| c.touches(f)))
                .collect();
            if hits.is_empty() {
                println!("None.\n");
            } else {
                for c in hits {
                    println!(
                        "- `{}:{}-{}` <-> `{}:{}-{}` ({} lines)",
                        c.file_a, c.a.0, c.a.1, c.file_b, c.b.0, c.b.1, c.lines
                    );
                }
                println!();
            }
        }
    }

    // --- semantic neighbors per changed function
    println!("## Similar existing code per changed function (embeddings)\n");
    println!("Similarity is rank-meaningful, not absolute — the top neighbor of a genuine re-implementation often scores ~0.5-0.7. Judge by reading the neighbor, not by the number.\n");
    let mut reported = 0usize;
    for &i in &changed_idx {
        let r = &st.records[i];
        if r.lines < min_lines || r.is_testish() {
            continue;
        }
        let mut sims: Vec<(f32, usize)> = st
            .vectors
            .iter()
            .enumerate()
            .filter(|(j, _)| {
                let o = &st.records[*j];
                // Skip self and anything overlapping it (nested extraction).
                *j != i && !(o.file == r.file && o.start <= r.end && r.start <= o.end)
            })
            .map(|(j, v)| (embedder::dot(&st.vectors[i], v), j))
            .collect();
        sims.sort_by(|x, y| y.0.total_cmp(&x.0));
        let neighbors: Vec<_> = sims
            .into_iter()
            .take(top)
            .filter(|(s, _)| *s >= 0.45)
            .collect();
        if neighbors.is_empty() {
            continue;
        }
        reported += 1;
        println!("### `{}`  ({}, {}L, {})", r.name, r.location(), r.lines, r.lang);
        for (s, j) in neighbors {
            let o = &st.records[j];
            let mut tags = Vec::new();
            if changed_set.contains(&j) {
                tags.push("also changed in this diff");
            }
            if o.is_testish() {
                tags.push("test code");
            }
            let tag = if tags.is_empty() {
                String::new()
            } else {
                format!("  [{}]", tags.join(", "))
            };
            let doc = if o.doc.is_empty() {
                String::new()
            } else {
                format!(" — {}", first_sentence(&o.doc))
            };
            println!("- {s:.2}  `{}`  {}{}{}", o.name, o.location(), doc, tag);
        }
        println!();
    }
    if reported == 0 {
        println!("No changed functions with notable neighbors.\n");
    }
    Ok(())
}
